### ISSUE TITLE
Értékelés

### ISSUE THREAD

**Issue by handras** [Teaching-projects/SZE-FordProg-2020-DBC#1]
Szia!

Nem tudom mennyi időt szánsz az átnézésre, ha futtatnád is, akkor python 3.7 és `pip install lark`.

A lényegi részek a következők:

- `grammar.lark:` ez a nyelvtan leírása BNF hez hasonló szintaxissal. A lexert automatikusan generálja, a nyelvtanban lévő literálokbó illetve a csupa nagybetűvel elnevezett  terminálokból.
- `DBC_transformer.py`: ebben a fájlban vannak a függvényeke, amiket parsolás közben a parser meghív, amikor egy adott csúcsot bejárt. A függvények nevei megegyeznek egy-egy szabály nevével a nyelvtanból. Ha nincs átalakító függvény definiálva akkor egy fa struktúrát épít a csúcsokból, ami egy flsőbb szinten feldolgozható
- `parser.py`: ebben van a main() definiálva, megnyitja a példa fájlt és mehívja rá a parsert. Breakpointot rakva a return elé vizsgálható a `CANdatabase`.

Itt egy példa a használatról:
```python
>>> print(database.nodes["MOTOR"].messages[0].message_name)
MOTOR_STATUS
>>> print("\t" + database.nodes["MOTOR"].messages[0].signals[0].name)
	MOTOR_STATUS_wheel_error
>>> print("\t" + database.nodes["MOTOR"].messages[0].signals[1].name)
	MOTOR_STATUS_speed_kph
```

A fájlba kiírást végül nem volt időm megcsinálni.

Horváth András

**Comment by hegyhati** [comment]
Szia! Ezt csak msot nezem a vizsga miatt, errol az issue-rol nem kaptam am ertesitest, mert nem rendeltel hozza :-) node lesem mindjart, csak elebb beirom a jegyet azoknak, akiknel mar eldolt.

**Comment by hegyhati** [comment]
Megneztem, lapaosan most nem volt idom vegigbogaraszni, de jo es osszetett dolognak tunik, Ha a readme-t meg kiegeszitened egy kicsit reszletesebb peldaval, azt megkoszonnem, de az otos jar.

**Comment by handras** [comment]
Nem vagyok jártas a githubon, azt gondoltam kapsz értesítést mivel te csináltad a repot, bocsi!
